icecast:
  image: moul/icecast
  volumes:
  - logs:/var/log/icecast2
  environment:
  - ICECAST_SOURCE_PASSWORD=nightvale
  - ICECAST_ADMIN_PASSWORD=nightvale
  ports:
  - 8000:8000
ezstream:
  build: ezstream
  volumes:
    - ./data:/data
  links:
    - icecast
webclient:
  image: pierrezemb/gostatic
  volumes:
  - "./client:/srv/http"
  ports:
  - 8080:8043
